name: Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: scoop install cppcheck
    - name: analyse
      run: cppcheck --enable=all 3_Implementation
